<?php

/**
 * @file
 * Teasearch Filter module hooks.
 */

/**
 * Implements hook_theme().
 *
 * @param array  $existing
 *   Pre-existing theme hook definitions.
 * @param string $type
 *   Invocation type ('module').
 * @param string $theme
 *   The active theme name.
 * @param string $path
 *   The base path to this module.
 *
 * @return array
 *   Theme hook definitions.
 */
function teasearch_filter_theme($existing, $type, $theme, $path)
{
  return [
    'teasearch' => [
      'variables' => [
        'filter_form' => NULL,
        'nodes' => NULL,
        'filters' => NULL,
        'grouped_filters' => NULL,
        'content_type' => NULL,
      ],
      'template' => 'teasearch',
    ],
  ];
}
