custom_field_graphql.subfield.*:
  type: mapping
  label: 'Subfield settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable field'
    name_sdl:
      type: string
      label: 'Schema field name'
