<?php

/**
 * @file
 * Teasearch Carousel module.
 */

function teasearch_carousel_theme($existing, $type, $theme, $path)
{
  return [
    'carousel_view_all' => [
      'variables' => [
        'news' => [],
        'highlights' => [],
      ],
      'template' => 'carousel-view-all',
    ],
    'news_view_all' => [
      'variables' => [
        'news' => [],
      ],
      'template' => 'news-view-all',
    ],
  ];
}
