include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  _TARGET_PHP: 8.3
  OPT_IN_TEST_CURRENT: 1
  OPT_IN_TEST_PREVIOUS_MAJOR: 1
  OPT_IN_TEST_PREVIOUS_MINOR: 1
  OPT_IN_TEST_NEXT_MINOR: 1
  #OPT_IN_TEST_NEXT_MAJOR: 1
  OPT_IN_TEST_MAX_PHP: 1
  _PHPUNIT_CONCURRENT: 1
  _CSPELL_IGNORE_PATHS: "'css'"

# 'Abuse' previous minor to test against D10.3 (LTS).
composer (previous minor):
  variables:
    DRUPAL_CORE: 10.3.14

cspell:
  allow_failure: true
phpcs:
  allow_failure: true
phpstan:
  allow_failure: true
